### ISSUE TITLE
Dynamic Bucket Usage (Buckets per hour)

### ISSUE THREAD

**Issue by blahaj-blast** [XVs32/kcauto_custom#30]
Since kcauto already tracks buckets and the delta per hour, it would be nice if we could set in the config an option to use buckets but keep a set hourly delta either positive to make sure we are stockpiling or negative to limit use to not blow through the stockpile.

**Comment by XVs32** [comment]
This shouldn't be that hard to achieve, 
though a simpler implementation could be telling kcauto to not use any if bucket is under a certain threshold.
Since usually what we want is a healthy number(say 1000) of buckets before an event.

I made a new branch here for now. https://github.com/XVs32/kcauto_custom/issues/35
