### ISSUE TITLE
KCAuto Custom will not sortie

### ISSUE THREAD

**Issue by Danielosama** [XVs32/kcauto_custom#61]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`):  **v8.1.0**
* Operating system and/or VM:  **Windows 10**

#### Issue variability
 **Consistent**

#### Issue

Sortie not possible:

![image](https://github.com/XVs32/kcauto_custom/assets/12687427/37ba1ef3-d51e-4967-b10e-b65687856ca9)

#### Config
```
"combat.enabled":	true,
	"combat.sortie_map":	"3-2",
	"combat.fleet_mode":	"standard",
	"combat.node_selects":	[],
	"combat.retreat_points":	[],
	"combat.push_nodes":	["A"],
	"combat.node_formations":	["1:echelon"],
	"combat.node_night_battles":	[],
	"combat.retreat_limit":	4,
	"combat.repair_limit":	4,
	"combat.repair_timelimit_hours":	0,
	"combat.repair_timelimit_minutes":	0,
	"combat.check_fatigue":	false,
	"combat.lbas_groups":	[],
	"combat.lbas_group_1_nodes":	[],
	"combat.lbas_group_2_nodes":	[],
	"combat.lbas_group_3_nodes":	[],
	"combat.check_lbas_fatigue":	false,
	"combat.port_check":	false,
	"combat.clear_stop":	false,
	"combat.reserve_repair_dock":	false,
	"combat.fleet_presets":	[],
```

**Comment by XVs32** [comment]
Hello [Danielosama](https://github.com/Danielosama),

This is probably the same problem here:
https://github.com/XVs32/kcauto_custom/issues/54

The fix is merged into `develop` branch, though it is not included in the current release pack yet.
https://github.com/XVs32/kcauto_custom/pull/55

You can either:
1. Wait for next release
2. Pull the latest `develop` from github yourself
3. Try editing `util\logger.py` line 21 to 
```cls.log_file = open( "log/" + dt_string + ".log", "w", encoding="utf-8")```

Sincerely,
XVs32

**Comment by Danielosama** [comment]
Strange, I launched the config with following command:

![image](https://github.com/XVs32/kcauto_custom/assets/12687427/ae6ea47f-2591-46cd-9292-5e6ba776a3b7)

I thought that would take care of it (it did in the original KCAutoKai).

**Comment by XVs32** [comment]
Me too thought tweaking the environment variable could do the trick but apparently it's not.
Maybe this is because kcauto_custom is writing into a file and the terminal, 
while the original KCAutoKai only writes into the terminal.

Anyway, I will only spend minimum effort on Windows fount, 
since I won't be using Windows version afterall...

**Comment by Danielosama** [comment]
I see, I wil try the 3rd option then and see how it goes.

```
Anyway, I will only spend minimum effort on Windows fount,
since I won't be using Windows version afterall...
```
That's perfectly understandable.
I will still open Issues for the Windows version if I ever get one if that's alright with you (the problem and/or solution might not be exclusive to the Windows version after all).

All best,

**Comment by XVs32** [comment]
```
I will still open Issues for the Windows version if I ever get one if that's alright with you 
```
Sure! 
What I mean is I will do my best to make sure the Windows version is at least useable.
Though I might not spend the extra effort to dig deep/optimize it.
So feel free to open issues when needed, I am happy to help.

Sincerely,
XVs32
